#!/usr/bin/env python3
"""
OSINT Report Generator
Generates formatted reports from OSINT data collection
"""

import json
import argparse
from datetime import datetime
from typing import Dict, Any, List
import os

def generate_markdown_report(data: Dict[str, Any], target: str) -> str:
    """Generate a Markdown formatted report"""
    report = f"""# OSINT Report: {target}

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}
**Tool:** Glitch OSINT Toolkit

---

## Executive Summary

Target: `{target}`
Data Sources Queried: {len(data.get('sources', []))}

---

## Findings

"""
    
    # Person data
    if 'person' in data:
        person = data['person']
        report += "### Person Information\n\n"
        if person.get('name'):
            report += f"- **Name:** {person['name']}\n"
        if person.get('email'):
            report += f"- **Email:** {person['email']}\n"
        if person.get('company'):
            report += f"- **Company:** {person['company']}\n"
        if person.get('title'):
            report += f"- **Title:** {person['title']}\n"
        if person.get('linkedin'):
            report += f"- **LinkedIn:** {person['linkedin']}\n"
        report += "\n"
    
    # Company data
    if 'company' in data:
        company = data['company']
        report += "### Company Information\n\n"
        if company.get('name'):
            report += f"- **Name:** {company['name']}\n"
        if company.get('domain'):
            report += f"- **Domain:** {company['domain']}\n"
        if company.get('industry'):
            report += f"- **Industry:** {company['industry']}\n"
        if company.get('employees'):
            report += f"- **Employees:** {company['employees']}\n"
        report += "\n"
    
    # Domain/Infrastructure
    if 'infrastructure' in data:
        infra = data['infrastructure']
        report += "### Infrastructure\n\n"
        if infra.get('ip_addresses'):
            report += "**IP Addresses:**\n"
            for ip in infra['ip_addresses']:
                report += f"- `{ip}`\n"
        if infra.get('subdomains'):
            report += "\n**Subdomains:**\n"
            for sub in infra['subdomains'][:20]:  # Limit to 20
                report += f"- `{sub}`\n"
        if infra.get('technologies'):
            report += "\n**Technologies Detected:**\n"
            for tech in infra['technologies']:
                report += f"- {tech}\n"
        report += "\n"
    
    # Social Media
    if 'social_media' in data:
        social = data['social_media']
        report += "### Social Media Presence\n\n"
        for platform, url in social.items():
            report += f"- **{platform}:** {url}\n"
        report += "\n"
    
    # Email addresses found
    if 'emails' in data:
        report += "### Email Addresses Found\n\n"
        for email in data['emails'][:30]:  # Limit
            report += f"- `{email}`\n"
        report += "\n"
    
    # Raw data
    if 'raw' in data:
        report += "### Raw Data\n\n```json\n"
        report += json.dumps(data['raw'], indent=2)[:5000]  # Limit size
        report += "\n```\n"
    
    report += """
---

## Methodology

This report was generated using the Glitch OSINT Toolkit, which queries multiple data sources including:
- Hunter.io (email discovery)
- Shodan (infrastructure scanning)
- Apollo (company/person data)
- LinkedIn (professional profiles)
- DNS/WHOIS records
- Social media platforms

---

*Report generated by Glitch ⚡*
"""
    return report


def generate_json_report(data: Dict[str, Any], target: str) -> str:
    """Generate JSON formatted report"""
    report = {
        "meta": {
            "target": target,
            "generated_at": datetime.now().isoformat(),
            "tool": "Glitch OSINT Toolkit"
        },
        "data": data
    }
    return json.dumps(report, indent=2)


def generate_html_report(data: Dict[str, Any], target: str) -> str:
    """Generate HTML formatted report"""
    md_content = generate_markdown_report(data, target)
    # Simple markdown to HTML conversion
    html = f"""<!DOCTYPE html>
<html>
<head>
    <title>OSINT Report: {target}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; }}
        h1, h2, h3 {{ color: #333; }}
        code {{ background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }}
        pre {{ background: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; }}
        ul {{ line-height: 1.8; }}
        hr {{ border: none; border-top: 1px solid #ddd; margin: 20px 0; }}
    </style>
</head>
<body>
<pre>{md_content}</pre>
</body>
</html>"""
    return html


def save_report(content: str, filename: str):
    """Save report to file"""
    with open(filename, 'w') as f:
        f.write(content)
    print(f"Report saved to: {filename}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate OSINT reports")
    parser.add_argument("target", help="Target of the investigation")
    parser.add_argument("-i", "--input", help="JSON input file with collected data")
    parser.add_argument("-o", "--output", help="Output filename")
    parser.add_argument("-f", "--format", choices=["md", "json", "html"], default="md", help="Output format")
    
    args = parser.parse_args()
    
    # Load data
    if args.input and os.path.exists(args.input):
        with open(args.input) as f:
            data = json.load(f)
    else:
        # Demo data
        data = {
            "sources": ["hunter", "shodan", "dns"],
            "person": {"name": args.target},
            "note": "No input data provided - this is a template"
        }
    
    # Generate report
    if args.format == "md":
        report = generate_markdown_report(data, args.target)
        ext = "md"
    elif args.format == "json":
        report = generate_json_report(data, args.target)
        ext = "json"
    else:
        report = generate_html_report(data, args.target)
        ext = "html"
    
    # Save or print
    if args.output:
        save_report(report, args.output)
    else:
        print(report)
